pub(super) fn key_identifier(identifier: &str) -> Option<&'static str> {
    const KEYS: &[&str] = &[
        "esc",
        "f1",
        "f2",
        "f3",
        "f4",
        "f5",
        "f6",
        "f7",
        "f8",
        "f9",
        "f10",
        "f11",
        "f12",
        "print_screen",
        "grave",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "minus",
        "equal",
        "backspace",
        "tab",
        "q",
        "w",
        "e",
        "r",
        "t",
        "y",
        "u",
        "i",
        "o",
        "p",
        "left_bracket",
        "right_bracket",
        "backslash",
        "caps_lock",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        "semicolon",
        "quote",
        "enter",
        "shift_left",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        "comma",
        "period",
        "slash",
        "shift_right",
        "ctrl_left",
        "win_left",
        "alt_left",
        "space",
        "alt_right",
        "win_right",
        "menu",
        "ctrl_right",
        "left_shift",
        "right_shift",
        "left_ctrl",
        "left_meta",
        "left_alt",
        "right_alt",
        "right_meta",
        "right_ctrl",
        "insert",
        "home",
        "page_up",
        "delete",
        "end",
        "page_down",
        "arrow_up",
        "arrow_left",
        "arrow_down",
        "arrow_right",
        "num_lock",
        "num_divide",
        "num_multiply",
        "num_minus",
        "num_7",
        "num_8",
        "num_9",
        "num_plus_1",
        "num_4",
        "num_5",
        "num_6",
        "num_plus_2",
        "num_1",
        "num_2",
        "num_3",
        "num_enter_1",
        "num_0",
        "num_decimal",
        "num_enter_2",
    ];
    KEYS.iter().copied().find(|key| *key == identifier)
}

pub(super) fn runtime_key_identifier(identifier: &str) -> &str {
    match identifier {
        "left_shift" => "shift_left",
        "right_shift" => "shift_right",
        "left_ctrl" => "ctrl_left",
        "right_ctrl" => "ctrl_right",
        "left_meta" => "win_left",
        "right_meta" => "win_right",
        "left_alt" => "alt_left",
        "right_alt" => "alt_right",
        "num_plus_2" => "num_plus_1",
        "num_enter_2" => "num_enter_1",
        identifier => identifier,
    }
}

pub(crate) fn canonical_key_identifier(identifier: &str) -> &str {
    match identifier {
        "shift_left" => "left_shift",
        "shift_right" => "right_shift",
        "ctrl_left" => "left_ctrl",
        "ctrl_right" => "right_ctrl",
        "win_left" => "left_meta",
        "win_right" => "right_meta",
        "alt_left" => "left_alt",
        "alt_right" => "right_alt",
        "num_plus_2" => "num_plus_1",
        "num_enter_2" => "num_enter_1",
        identifier => identifier,
    }
}
